org: nsx07
service: leads-api

plugins:
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs18.x

  environment:
    iamRoleStatements: ${file(iam/leadsTableIAM.yml)}

resources:
  Resources:
    leadsTable: ${file(resources/leadsTable.yml):leadsTable}

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
