# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nsx07
service: serverless-example

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
